train: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\3.dataset-origin+20dB_defaultcolor_usingAG\dataset_aug\train  # 数据集路径
val: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\3.dataset-origin+20dB_defaultcolor_usingAG\dataset_aug\valid  # 数据集路径
save_path: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\3.dataset-origin+20dB_defaultcolor_usingAG\exp\11.vit_l_32
model : vit_l_32
weights: None
batch_size: 8
image_size: 224
num_classes: 5
class_names: [S
        'DJIAVATA2',
        'DJIFPVCOMBO',
        'DJIMAVIC3PRO',
        'DJIMINI3',
        'DJIMINI4PRO',
]
device: 'cuda'
num_epochs: 150
shuffle: True
lr: 0.00001
optimizer: None
