train: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\2.dataset-20dB_hot_usingAG\dataset_aug\train  # 数据集路径
val: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\2.dataset-20dB_hot_usingAG\dataset_aug\valid  # 数据集路径
save_path: E:\Drone_dataset\RFUAV\augmentation_exp1_MethodSelect\2.dataset-20dB_hot_usingAG\exp\2.ResNet34
model : resnet34  # 模型种类
weights: None  # 预训练模型路径
batch_size: 8
image_size: 640
num_classes: 5  # 种类数量
class_names: [
        'DJIAVATA2',
        'DJIFPVCOMBO',
        'DJIMAVIC3PRO',
        'DJIMINI3',
        'DJIMINI4PRO',
]
device: 'cuda' # 使用的训练设备
num_epochs: 150
shuffle: True
lr: 0.0001
optimizer: None
