# 主要是给inference用，inference使用build获取模型训练过程中使用meta info，训练时又可以手动设参又可以用CFG
train: E:\Dataset_log\drone_thesis_classification_v2\train  # 数据集路径
val: E:\Dataset_log\drone_thesis_classification_v2\valid  # 数据集路径
save_path: E:\Train_log\Drone_thesis\Classification\ResNet152\exp5_classtest
model : resnet152  # 模型种类
weights: E:\Train_log\Drone_thesis\Classification\ResNet152\exp4_codecheck\best_model.pth  # 预训练模型路径
batch_size: 8
image_size: (224, 224)
num_classes: 23  # 种类数量
class_names: [
    'yunzhuoT12',
    'Vbar',
    'Tarains_Plus_FLY',
    'RadioLinkAT9S',
    'Phantom4ProRTK',
    'Phantom4Pro',
    'Phantom3',
    'Mini3Pro',
    'Mini2',
    'MavicPro',
    'Mavic3',
    'Matrice600Pro',
    'Matrice300',
    'Matrice200',
    'Matrice100',
    'Matrice30T',
    'Inspire2',
    'FutabaT61Z',
    'FutabaT14SG',
    'FrskyX20',
    'DJi',
    'AVATA',
    'Air2S'
]  # 类别
device: 'cuda' # 使用的训练设备
epochs: 100